### ISSUE TITLE
unfolding QuantumEspresso spin-orbit coupling bands (NbSe2 supercell)

### ISSUE THREAD

**Issue by gmm05126** [band-unfolding/banduppy#14]
Dear Stepan,

I am experiencing the following issue when unfolding bandstructure of 2x2 supercell of NbSe2 to hexagonal PC of NbSe2. A typical feature of the transition metal dichalcogenides is the spin splitting at the K point of about hundred of meV, seen as two spin split bands. The present implementation using DFT pw caculations QE v6.5 and unfolding using banduppy-0.1.3 and irrep-1.6.1 gives a single band, see figure left. The expected results with spin split bands is sketched with green lines on the right. The degen_thresh (in .../irrep/kpoint.py) was set well below the known band spin splitting.

![image](https://user-images.githubusercontent.com/4368441/147914499-687e709c-6bdb-4620-8b6f-f550993bc4a5.png)

The relevant pieces of the code are as follows

`unfold=banduppy.UnfoldingPath(
            supercell= [[ 2 ,  0 ,  0],
                        [ 0 ,  2 ,  0],
                        [ 0 ,  0 ,  1]] ,  
            pathPBZ=[[0,0,0],[1/3,1/3,0],[1/2,0,0],[0,0,0]],  
            nk=(32,12,32),
            labels="GKMG" )`

`bands=banduppy.BandStructure(code="espresso", prefix="nbse2")`

`unfold.plot(save_file="unfold_density.png",plotSC=True,Emin=-5,Emax=3.5,Ef=0.3674,mode='density',smear=0.015,nE=800)`

Input for quantum espresso (with cheap cutoffs):

 &CONTROL
                 title = 'NbSe2 2x2 for testing' ,
                 calculation = 'scf' ,
                restart_mode = 'from_scratch' ,
    pseudo_dir   = './pseudo',
                outdir = '/tmp',
                      prefix = 'nbse2' ,
                   verbosity = 'high' ,
 /
 &SYSTEM
                       ibrav = 4,
                   celldm(1) = 13.001316 ,
                   celldm(3) = 2.325 ,
                         nat = 12,
                        ntyp = 2,
                     ecutwfc = 55 ,
                     ecutrho = 437 ,
                    occupations = 'smearing' ,
                    degauss = 0.01 ,
                    noncolin = .true. ,
                    lspinorb = .true. ,
 /
 &ELECTRONS
                 startingpot = 'file' ,
                 conv_thr = 1.0d-09 ,
                 mixing_mode = 'plain' ,
                 mixing_beta = 0.7 ,
             diagonalization = 'david' ,
 /
ATOMIC_SPECIES
Nb  92.90638   Nb.rel-pbesol-spn-rrkjus_psl.1.0.0.UPF
Se  78.96      Se.rel-pbesol-n-rrkjus_psl.1.0.0.UPF
ATOMIC_POSITIONS  crystal 
Nb   0.16666666   0.33333334   0.00000000
Nb   0.66666666   0.33333334   0.00000000
Nb   0.16666666   0.83333334   0.00000000
Nb   0.66666666   0.83333334   0.00000000
Se   0.33333334   0.16666666   0.11456888
Se   0.33333334   0.16666666   0.88543111
Se   0.83333334   0.16666666   0.11456888
Se   0.83333334   0.16666666   0.88543111
Se   0.33333334   0.66666666   0.11456888
Se   0.33333334   0.66666666   0.88543111
Se   0.83333334   0.66666666   0.11456888
Se   0.83333334   0.66666666   0.88543111
K_POINTS automatic
  6  6  1   0   0   0

The k-point list for bands calculations:
K_POINTS crystal
72
  0.00000000    0.00000000    0.00000000    1
  0.02150538    0.02150538    0.00000000    1
  0.03225806    0.00000000    0.00000000    1
  0.04301075    0.04301075    0.00000000    1
  0.06451613    0.06451613    0.00000000    1
  0.06451613    0.00000000    0.00000000    1
  0.08602151    0.08602151    0.00000000    1
  0.09677419    0.00000000    0.00000000    1
  0.10752688    0.10752688    0.00000000    1
  0.12903226    0.00000000    0.00000000    1
  0.12903226    0.12903226    0.00000000    1
  0.15053763    0.15053763    0.00000000    1
  0.16129032    0.00000000    0.00000000    1
  0.17204301    0.17204301    0.00000000    1
  0.19354839    0.19354839    0.00000000    1
  0.19354839    0.00000000    0.00000000    1
  0.21505376    0.21505376    0.00000000    1
  0.22580645    0.00000000    0.00000000    1
  0.23655914    0.23655914    0.00000000    1
  0.25806452    0.00000000    0.00000000    1
  0.25806452    0.25806452    0.00000000    1
  0.27956989    0.27956989    0.00000000    1
  0.29032258    0.00000000    0.00000000    1
  0.30107527    0.30107527    0.00000000    1
  0.32258065    0.32258065    0.00000000    1
  0.32258065    0.00000000    0.00000000    1
  0.34408602    0.34408602    0.00000000    1
  0.35483871    0.00000000    0.00000000    1
  0.36559140    0.36559140    0.00000000    1
  0.38709677    0.38709677    0.00000000    1
  0.38709677    0.00000000    0.00000000    1
  0.40860215    0.40860215    0.00000000    1
  0.41935484    0.00000000    0.00000000    1
  0.43010753    0.43010753    0.00000000    1
  0.45161290    0.45161290    0.00000000    1
  0.45161290    0.00000000    0.00000000    1
  0.47311828    0.47311828    0.00000000    1
  0.48387097    0.00000000    0.00000000    1
  0.49462366    0.49462366    0.00000000    1
  0.51612903    0.00000000    0.00000000    1
  0.64516129    0.64516129    0.00000000    1
  0.51612903    0.51612903    0.00000000    1
  0.53763441    0.53763441    0.00000000    1
  0.54838710    0.00000000    0.00000000    1
  0.55913978    0.55913978    0.00000000    1
  0.58064516    0.58064516    0.00000000    1
  0.58064516    0.00000000    0.00000000    1
  0.60215054    0.60215054    0.00000000    1
  0.61290323    0.00000000    0.00000000    1
  0.62365591    0.62365591    0.00000000    1
  0.64516129    0.00000000    0.00000000    1
  0.64516129    0.64516129    0.00000000    1
  0.66666667    0.66666667    0.00000000    1
  0.67741935    0.00000000    0.00000000    1
  0.69696970    0.60606061    0.00000000    1
  0.70967742    0.00000000    0.00000000    1
  0.72727273    0.54545455    0.00000000    1
  0.74193548    0.00000000    0.00000000    1
  0.75757576    0.48484848    0.00000000    1
  0.77419355    0.00000000    0.00000000    1
  0.78787879    0.42424242    0.00000000    1
  0.80645161    0.00000000    0.00000000    1
  0.81818182    0.36363636    0.00000000    1
  0.83870968    0.00000000    0.00000000    1
  0.84848485    0.30303030    0.00000000    1
  0.87096774    0.00000000    0.00000000    1
  0.87878788    0.24242424    0.00000000    1
  0.90322581    0.00000000    0.00000000    1
  0.90909091    0.18181818    0.00000000    1
  0.93548387    0.00000000    0.00000000    1
  0.93939394    0.12121212    0.00000000    1
  0.96774194    0.00000000    0.00000000    1
  0.96969697    0.06060606    0.00000000    1

The pseudopotentials can be found [here](https://webdisk.science.upjs.sk/~martin_gmitra/tmp/). Any hints or advises are very welcome.

Best regards,
Martin Gmitra

**Comment by stepan-tsirkin** [comment]
@gmm05126 , could you show the bandstructure (notunfolded) of the supercell. Near the point to which K folds. I guess it is also Kpoint. Is the band split there?

Is the band splitwhen you do the PC calculation?

**Comment by gmm05126** [comment]
@stepan-tsirkin
in both the band structure calculations, PC and SC, the bands are spin split at the K point (path length 0.66666) in the figures below.
![image](https://user-images.githubusercontent.com/4368441/147938204-b54880bf-c167-4840-ad83-bf5b8a21c84f.png)

**Comment by stepan-tsirkin** [comment]
I see, this is weird. The calculation you show is a perfect SC, right? So, the unfolded bandstructure should look exactly likethe PC calculation. 

Note, there is another issue #9 related to the problem. I will investigate this.

**Comment by gmm05126** [comment]
@stepan-tsirkin
Yes, it is perfect SC, two times larger, and the unfolded bandstructure should look like the PC. The generated k-path (magenta points) for the unfolding along the G-K-M-G for the PC (green BZ) using `unfold.kpoints_SBZ_str()` is correct and it is exactly two times the SC (black BZ) as shows the figure.

![image](https://user-images.githubusercontent.com/4368441/148032516-f48bd3e8-de98-47fc-a12b-80687245efc8.png)

**Comment by stepan-tsirkin** [comment]
@gmm05126  , I fixed the bug, see #9 

please, tell me if ti works.

**Comment by gmm05126** [comment]
Dear Stepan,
Thank you for the update. I think it works now as it should be, see below comparison of PC (left) and SC (right).
Best,
Martin

![image](https://user-images.githubusercontent.com/4368441/165132693-c1daaa5e-fb47-4c0c-9c30-75476694aa48.png)

**Comment by stepan-tsirkin** [comment]
@gmm05126 Great!
I am closing the issue, if you have further problems reopen it (or open a new one)
