### ISSUE TITLE
error in running banduppy

### ISSUE THREAD

**Issue by mohammedalgeria** [band-unfolding/banduppy#2]
Hello
i have been trying to run banduppy uptonow i m getting the eerror:
error while unpickling unfold '[Errno 2] No such file or directory: 'unfold.pickle'',  unfolding it
unpickling bandstructure

followed by several lines concerning the unfinding of kpoints
any help is welcome

**Comment by stepan-tsirkin** [comment]
Dear @mohammedalgeria  , please show the full output of your run

**Comment by mohammedalgeria** [comment]
i m putting three files in google drive :

https://drive.google.com/file/d/16-ozlSX3F5wYfi6x4XlXtxkTA6d0pv9a/view?usp=sharing

**Comment by stepan-tsirkin** [comment]
dear @mohammedalgeria  , could you make the link publically accessible to anyone

**Comment by mohammedalgeria** [comment]
https://drive.google.com/file/d/16-ozlSX3F5wYfi6x4XlXtxkTA6d0pv9a/view?usp=sharing

**Comment by stepan-tsirkin** [comment]
dear @mohammedalgeria  , in the files you provided there is no output of banduppy, only output of quantum espresso.  There is a problem in diagonalization, but it is not related to banduppy, please study the documentation of QE, or the corresponding forums. 

The example script is written using raising and handling Exceptions, i.e. when something cannot be read - it will be calculated. So such an exception is not really an error, just information that data from previous runs were not read , which makes sence if you are running for the firsta time, or did not succeed in the previous runs.

Regards,
Stepan.

**Comment by mohammedalgeria** [comment]
thanks
