### ISSUE TITLE
Mirror bands 

### ISSUE THREAD

**Issue by w-yuxuan** [band-unfolding/banduppy#22]
Hi Dr. Tsirkin and the band up team,
Thank you for making the amazing code again! I found the following unfolded structure to have some mirror bands (ex. G-X). The same structure calculated in QE and unfolded with a different code did not show this suspicious feature.
I did see the warning                             'WARNING (point_is_in_bz): Tolerance applied &
                            when checking whether point lies inside 1BZ. ,&
                            This should be OK, but do check your results.'
Yet not using symmetry averaging had the same issue without this message.

Do you have any tricks to resolves this?
Does band up py use Bandup's unfolding algorithm for the most part? If not then I'm planning to try that. Thank you so much!

![unfolded_EBS_symmetry-averaged_E_from_-4 0_to_3 9999999999998295_eV_dE_0 004999999999999893_eV](https://github.com/band-unfolding/banduppy/assets/111606884/c4a65008-1a1d-4051-9418-0f6f6b272251)

**Comment by stepan-tsirkin** [comment]
Hi @w-yuxuan ,
Could you show what you get with QE and "the different code" (btw, which one, if not a secret), to understand what is the issue. Is the banduppy figure above NOT from QE, but other DFT code? 

without knowing your supercell and primitive cell I cannot understand if the result is wrong or not. 
attaching full log of the calculation is also often helpful. to understand what is going on.

Banduppy basically does the same algorithm as BandUP, but the implementation is separate, actually it mostly relies on [irrep](https://github.com/stepan-tsirkin/irrep) module.

**Comment by w-yuxuan** [comment]
Thank you so much for your quick response!
The figure above was using VASP and unfolded with band up.
The same structure calculated with QE and unfolded with a code by my collaborator gave. 

It turns out that the weights around X point are very small so when I increase the Vmin slightly they went away :) Probably they are from fine size effects.
