### ISSUE TITLE
question regarding band-resolved unfolding

### ISSUE THREAD

**Issue by NickRybin** [band-unfolding/banduppy#4]
Hi! My name is Nikita Rybin. I am a PhD student from Fritz-Haber institute. Recently, I became aware of bandup and decided to try it since my project is also related to band-unfolding. Since I had problems running bandup with QE I moved to banduppy. It works for me quite smoothly -- thanks @stepan-tsirkin for making it!

Although it works I have a question regarding the methodology and capabilities: as far as I understand, at the moment only momentum-resolved spectral function could be calculated, in other words for each k vector we unfold all the states of the supercell into the unit cell (eq.4 from Medeiros_PRB 2014 or appendix from PopescuZunger_PRB_2012 paper). 

However, I am interested in band-resolved spectral function, i.e., the projection of all the states from the supercell to some (let's say all valence and only a couple of first states in conduction zone) of the unit cell states. Could developers (@paulovcmedeiros  and @stepan-tsirkin ) give a bit more color on this question? Is there any probability that band-resolved case would be implemented soon?

Thank you!
Nikita

**Comment by stepan-tsirkin** [comment]
Hi Nikita,

Yes, bandup(py) is unfolding to "all the states", which has a big advantage that we do not need to know those states.  In fact, we do not even need to know the atomic  structure of this "primitive cell", only it's basis vectors are used.

Projecting to particular bands can be done in principle, just for that one needs to calculate those states . There is one difficulty though, which is connected to PAW/ultrasoft pseudopotentials. That is, now we use only the plane-wave part of the wavefuncions, bnot the "all-electron" one. This is fine for the unfolding, but for projecting onto particular bands it may give serious errors. Therefore such projection may be done relatively easy only for norm-conserving pseudopotentials.

However, I wonder in what case you expect the result to be crucially different from "projecting to all bands" and what new physical information you would like to extract from such projection?

**Comment by NickRybin** [comment]
Hi, Stepan! Yeap, I understand the point that no knowledge of the primitive cell is required and this simplifies the calculations. However,  if I want to fit the spectrum with lorentzians and extract information about spectral function spreading / peak position (I saw that in paper this is done differently), it looks like it would be easier to fit one band after another one, rather than all of them simultaneously.

**Comment by stepan-tsirkin** [comment]
Ok, I see, so you want to unfold it first to one band, then to another. I will think of how to implement it. However, not sure if the result will be what you are expecting.
